### ISSUE TITLE
没有install目录

### ISSUE THREAD

**Issue by xiao8Git** [Cryin/Startblog#1]
没有install目录，安装时出现404

**Comment by Cryin** [comment]
thx，近期会对UI进行一次全面升级，到时会一同解决这个问题。

**Comment by Cryin** [comment]
安装向导已更新，采用Amazeui全面升级后台及前端UI，请下载最新版再次尝试安装。

有些环境下可能会出现找不到model的问题，这种情况把application\models\ 下所有文件首字母改成大写即可

如果安装在目录则根据站点目录修改.htaccess文件Rewrite规则，并修改application\config\config.php文件，添加目录字段： $config['base_url'] = 'http://'.$_SERVER['SERVER_NAME'].'/mulu';
