### ISSUE TITLE
检查你的SQL是否暴露了你的密码？

### ISSUE THREAD

**Issue by JunJun-Love-Amber** [Cryin/Startblog#2]
INSERT INTO `user` VALUES ('1', 'startblog', '2f780b5a7762af9c258076e913178715', 'assetsview@sina.cn');

**Comment by Cryin** [comment]
感谢提交反馈，我查看了下这句是在sql文件中，sql文件中的帐号密码为初始化帐号密码，在安装使用说明中也有告知，用户安装后可以修改，不存在信息泄露风险。
不过还是谢谢提醒，因为我的demo站点使用的是默认初始化密码。我稍后会进行修改~。
