### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by kukudeliu** [Cryin/Startblog#3]
1.CI3.0以后的版本，类名需要大写（Model）。
2.类名和文件名应该一致，包括扩展核心系统类（MY_Controller=》Controller）。
3.$this->input->post('name', True);  传值应该过滤。
4.Session类和database类，常用类，自动加载就行，autoload.php配置。
5.类加载Model放构造方法中就行吧，减少代码。
6.分页类配置，这个可以提个共通，减少代码。搜了一下好些地方用。
7.总结：原生PHP写多了...才会产生一些问题

**Comment by Cryin** [comment]
谢谢这些建议，我看了下基本上都是程序存在的一些问题，在下个版本我会整体进行改进、修复。good luck！

**Comment by kukudeliu** [comment]
@Cryin 做产品这个我不懂，至于前端和后台整个博客怎么操作流程，每个人想法都不一样，这也是你这个博客的风格，咱们也不能照搬（XX框架-》CI），这么做其实也没啥意义了，保持下去就好，干吧得！！！

**Comment by Cryin** [comment]
2016.11.25  v2.1更新记录

*新增友情链接编辑、排序功能

*修改文件编辑界面，增加编辑框边框

*修复dreamkill同学提出的bug及程序问题，输入输出统一进行安全过滤，model类修改为大写

*Session类和database类自动加载

还有一些后续慢慢改进优化，我先把这个issues关闭了~
