### ISSUE TITLE
追加文章编辑，没有填写封面图链接时，随机一张图片

### ISSUE THREAD

**Issue by kukudeliu** [Cryin/Startblog#4]
文件夹：view
文件名：articles_index.php
行号：21行
`<img src="<?php echo $value['imagelink'] == '' ? json_decode(file_get_contents('http://bing.ioliu.cn/v1/rand?type=json'))->data->bmiddle_pic : $value['imagelink']?>" alt="封面配图" class="am-u-sm-12">`

直接替换即可

**Comment by Cryin** [comment]
已替换为上述随机图片展示~thx
