### ISSUE TITLE
http://localhost/startblog/install 安装时候出错

### ISSUE THREAD

**Issue by liuzedong** [Cryin/Startblog#8]
访问路径:http://192.168.1.100/startblog/
等待一会都超时,返回
**http://localhost/startblog/install**
 
我使用的是IP进行访问的, 数据库的配置,用户名,密码和库都改啦,.htaccess 文件也修改啦,  但是出现这个错,我是在局域网中搭建的,没有使用域名.

第一次玩PHP,希望大神解惑.

**Comment by liuzedong** [comment]
运行环境，nginx+php+mysql,
phpmyadmim安装是成功，
和运行环境有关吗？

**Comment by Cryin** [comment]
是环境问题，我只在apache mysql下测试过，nginx是有问题，一是rewrite规则可能有问题，另一个程序也没在nginx下测试过。如果条件允许的话可以改用apache安装试试

**Comment by liuzedong** [comment]
好的，谢谢，新年快乐

**Comment by Cryin** [comment]
thx,nginx环境下会在后续进行兼容完善
